QuanLiCuaHang/Areas/Manager/Controllers/LOAISPController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuanLiCuaHang.Areas.Manager.Data;
using QuanLiCuaHang;

namespace QuanLiCuaHang.Areas.Manager.Controllers
{
    public class LoaiSPController : Controller
    {
        private QUANLYCUAHANGEntity db = new QUANLYCUAHANGEntity();

        // GET: Manager/LOAISP
        public ActionResult Index()
        {
            var lOAISANPHAM = new LOAISANPHAM();
            ViewBag.MaDVT = new SelectList(db.DONVITINHs, "MaDVT", "TenDVT");
            return View(lOAISANPHAM);
        }

        public ActionResult Details()
        {
            var lOAISANPHAMs = db.LOAISANPHAMs.Include(l => l.DONVITINH);
            ViewBag.MaDVT = new SelectList(db.DONVITINHs, "MaDVT", "TenDVT");
            return View(lOAISANPHAMs.ToList());
        }
            

        //CheckTenLoaiSP
        public JsonResult IsTenLoaiSPavailable(string TenLoaiSP)
        {
            return Json(!db.LOAISANPHAMs.Any(x => x.TenLoaiSP == TenLoaiSP), JsonRequestBehavior.AllowGet);
        }









        // GET: Manager/LOAISP/ChiTiet/5
        public ActionResult ChiTiet(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LOAISANPHAM lOAISANPHAM = db.LOAISANPHAMs.Find(id);
            if (lOAISANPHAM == null)
            {
                return HttpNotFound();
            }
            return View(lOAISANPHAM);
        }



        // POST: Manager/LOAISP/Tao
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index([Bind(Include = "MaLoaiSP,TenLoaiSP,PhanTramLoiNhuan,MaDVT")] LOAISANPHAM lOAISANPHAM)
        {




            if (ModelState.IsValid)
            {
                db.LOAISANPHAMs.Add(lOAISANPHAM);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaDVT = new SelectList(db.DONVITINHs, "MaDVT", "TenDVT", lOAISANPHAM.MaDVT);
            return View(lOAISANPHAM);
        }

        // GET: Manager/LOAISP/Sua/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LOAISANPHAM lOAISANPHAM = db.LOAISANPHAMs.Find(id);
            if (lOAISANPHAM == null)
            {
                return HttpNotFound();
            }
            //ViewBag.MaDVT = new SelectList(db.DONVITINHs, "MaDVT", "TenDVT", lOAISANPHAM.MaDVT);
            return View(lOAISANPHAM);
        }

        // POST: Manager/LOAISP/Sua/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaLoaiSP,TenLoaiSP,PhanTramLoiNhuan,MaDVT")] LOAISANPHAM lOAISANPHAM)
        {
            if (ModelState.IsValid)
            {
                db.Entry(lOAISANPHAM).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            //ViewBag.MaDVT = new SelectList(db.DONVITINHs, "MaDVT", "TenDVT", lOAISANPHAM.MaDVT);
            return View(lOAISANPHAM);
        }

        // GET: Manager/LOAISP/Xoa/5
        public ActionResult Xoa(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LOAISANPHAM lOAISANPHAM = db.LOAISANPHAMs.Find(id);
            if (lOAISANPHAM == null)
            {
                return HttpNotFound();
            }
            return View(lOAISANPHAM);
        }

        // POST: Manager/LOAISP/Xoa/5
        [HttpPost, ActionName("Xoa")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            LOAISANPHAM lOAISANPHAM = db.LOAISANPHAMs.Find(id);
            db.LOAISANPHAMs.Remove(lOAISANPHAM);
            db.SaveChanges();
            return RedirectToAction("DanhSach");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuanLiCuaHang/Areas/Manager/Views/LOAISP/Details.cshtml
@model IEnumerable<QuanLiCuaHang.Areas.Manager.Data.LOAISANPHAM>


<div class="card mb-4">
    <div class="card-header"><b>DANH MỤC CÁC LOẠI SẢN PHẨM</b></div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered table-striped mb-none" id="datatable-editable" width="100" cellspacing="0">
                <thead>
                    <tr>
                        <th>Mã loại sản phẩm</th>
                        <th>Tên loại sản phẩm</th>
                        <th>Phần trăm lợi nhuận</th>
                        <th>Đơn vị tính</th>
                        <th>Thao tác</th>
                    </tr>
                </thead>
                <tbody>


                    @foreach (var item in Model)
                    {

                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.MaLoaiSP)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.TenLoaiSP)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PhanTramLoiNhuan)%
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DONVITINH.TenDVT)
                            </td>
                            <td class="actions" style="text-align:center">
                                <a href='@Url.Action("Edit","LoaiSP",new { id = item.MaLoaiSP })'>
                                    <i type="button" class="fa fa-pencil fa-2x"> </i>
                                </a>
                            </td>
                        </tr>

                    }

                </tbody>
            </table>
        </div>
    </div>
</div>

QuanLiCuaHang/Areas/Manager/Views/LOAISP/Edit.cshtml
@model QuanLiCuaHang.Areas.Manager.Data.LOAISANPHAM

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Manager/Views/Shared/_Layout.cshtml";
}


<script src="~/Scripts/jquery-3.4.1.min.js"></script>

<script src="~/Scripts/jquery.validate.min.js"></script>

<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

<script type="text/javascript">

    $(document).ready(function () {
        
                    $("#addToTable").click(function (event) {

                        var error_free = true;


                        if ($(".input-validation-error").length != 0) {
                            error_free = false;
                        }


                        if (!error_free) {
                            event.preventDefault();
                            swal({
                                title: "Lỗi !",
                                text: "Cập nhật thất bại!",
                                icon: "error",
                                button: "Đồng ý!",
                            });
                        }
                        else {
                            swal({
                                title: "Thành công !",
                                text: "Cập nhật thành công!",
                                icon: "success",
                                button: "Đồng ý!",
                            });
                        }

                    });

    });
</script>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <style>
        #nhapphieu {
            text-align: center;
            color: purple;
            font-size: 35px;
            font-weight: bold;
            /*border: 1px solid #ddd;
            background-color: forestgreen;*/
            padding: 0px 0px;
            margin: 0px 290px;
        }
    </style>

    @* End CSS *@

    <h1 id="nhapphieu">SỬA LOẠI SẢN PHẨM</h1>
    <br />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.MaLoaiSP)

    <div class="form-group">
        @Html.LabelFor(model => model.TenLoaiSP, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10" style="padding-top:10px">

            @Html.DisplayFor(model => model.TenLoaiSP, new { htmlAttributes = new { @class = "form-control" } })
            @Html.HiddenFor(model => model.TenLoaiSP, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenLoaiSP, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.PhanTramLoiNhuan, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PhanTramLoiNhuan, new { htmlAttributes = new { @class = "form-control", type = "number" } })
            @Html.ValidationMessageFor(model => model.PhanTramLoiNhuan, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MaDVT, "Tên đơn vị tính", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10" style="padding-top: 10px">
            @Html.HiddenFor(model => model.MaDVT)
            @Html.DisplayFor(model => model.DONVITINH.TenDVT, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MaDVT, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input id="addToTable" type="submit" value="Lưu" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Trở về", "Index")
</div>

QuanLiCuaHang/Areas/Manager/Views/LOAISP/Index.cshtml
@model QuanLiCuaHang.Areas.Manager.Data.LOAISANPHAM

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Manager/Views/Shared/_Layout.cshtml";
}

<script src="~/Scripts/jquery-3.4.1.min.js"></script>

<script src="~/Scripts/jquery.validate.min.js"></script>

<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<head>
    <meta charset="utf-8" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Danh sách các loại sản phẩm</title>


</head>

<script type="text/javascript">



    $(document).ready(function () {
        $("#addToTable").click(function (event) {

            var error_free = true;


            if ($(".input-validation-error").length != 0) {
                error_free = false;
            }

            if ($("#TenLoaiSP").val() == '') {
                error_free = false;
            }

            if (!error_free) {
                event.preventDefault();
                swal({
                    title: "Lỗi !",
                    text: "Thêm mới thất bại!",
                    icon: "error",
                    button: "Đồng ý!",
                });
            }
            else {
                swal({
                    title: "Thành công !",
                    text: "Thêm mới thành công!",
                    icon: "success",
                    button: "Đồng ý!",
                });
            }

        });
    });
</script>
<main>
    <style>
        #nhapphieu {
            text-align: center;
            color: purple;
            font-size: 35px;
            font-weight: bold;
            /*border: 1px solid #ddd;
            background-color: forestgreen;*/
            padding: 0px 0px;
            margin: 0px 290px;
        }
    </style>

    @* End CSS *@

    <h1 id="nhapphieu">LOẠI SẢN PHẨM</h1>
    <br />

    <div class="container-fluid">
        <div col="mb-4">

            <div class="card mb-4">
                <div class="card-header"><b>THÊM MỚI LOẠI SẢN PHẨM</b></div>
                <div class="card-body">
                    @using (Html.BeginForm())
                    {@Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <form action="/action_page.php" class="needs-validation" novalidate>

                        <div class="form-row">
                            <div class="form-group col-sm-3" hidden>

                                @Html.HiddenFor(model => model.MaLoaiSP, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.MaLoaiSP, "", new { @class = "text-danger" })
                                <div class="invalid-feedback">Vui lòng nhập đầy đủ thông tin về mã loại sản phẩm</div>



                            </div>
                            <div class="form-group col-sm-3">
                                <label>Tên loại sản phẩm</label>

                                @Html.EditorFor(model => model.TenLoaiSP, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.TenLoaiSP, "", new { @class = "text-danger" })

                            </div>
                            <div class="form-group col-sm-3">
                                <label for="donvitinh">Đơn vị tính</label>

                                @Html.DropDownList("MaDVT", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.DONVITINH, "", new { @class = "text-danger" })

                                <div class="invalid-feedback">Vui lòng nhập đầy đủ thông tin về đơn vị tính</div>
                            </div>


                        </div>
                        <div class="form-row">
                            <div class="form-group col-sm-3">
                                <label>Phần trăm lợi nhuận</label>

                                @Html.EditorFor(model => model.PhanTramLoiNhuan, new { htmlAttributes = new { @class = "form-control", type = "number" } })
                                @Html.ValidationMessageFor(model => model.PhanTramLoiNhuan, "", new { @class = "text-danger" })

                                <div class="invalid-feedback">Vui lòng nhập đầy đủ thông tin về phần trăm lợi nhuận</div>
                            </div>

                        </div>

                        <input type="submit" id="addToTable" class="btn btn-primary" value="Thêm" />

                    </form>
                }
                </div>
            </div>
        </div>
             @Html.Action("Details")



    </div>
</main>

<!-- Vendor -->
<script src="~/Assets/Manager/dist/assets/vendor/jquery/jquery.js"></script>
<script src="~/Assets/Manager/dist/assets/vendor/jquery-browser-mobile/jquery.browser.mobile.js"></script>
<script src="~/Assets/Manager/dist/assets/vendor/bootstrap/js/bootstrap.js"></script>
<script src="~/Assets/Manager/dist/assets/vendor/nanoscroller/nanoscroller.js"></script>
<script src="~/Assets/Manager/dist/assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
<script src="~/Assets/Manager/dist/assets/vendor/magnific-popup/magnific-popup.js"></script>
<script src="~/Assets/Manager/dist/assets/vendor/jquery-placeholder/jquery.placeholder.js"></script>
<!-- Specific Page Vendor -->
<script src="~/Assets/Manager/dist/assets/vendor/select2/select2.js"></script>
<script src="~/Assets/Manager/dist/assets/vendor/jquery-datatables/media/js/jquery.dataTables.js"></script>
<!-- Examples -->
@*<script src="~/Assets/Manager/dist/assets/javascripts/tables/examples.datatables.editable.js"></script>*@
<script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
<script src="~/Assets/Manager/dist/js/scripts.js"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
@*</body>
    </html>*@

<style>


    .dataTables_paginate {
        float: right;
        text-align: right;
        padding-top: 0.25em
    }

    .dataTables_wrapper .dataTables_paginate .paginate_button {
        box-sizing: border-box;
        display: inline-block;
        min-width: 1.5em;
        padding: 0.5em 1em;
        margin-left: 2px;
        text-align: center;
        text-decoration: none !important;
        cursor: pointer;
        /**cursor: hand;*/
        color: #007bff !important;
        border: 1px solid transparent;
        border-radius: 2px
    }

        .dataTables_wrapper .dataTables_paginate .paginate_button.current, .dataTables_wrapper .dataTables_paginate .paginate_button.current:hover {
            color: #333 !important;
            border: 1px solid #979797;
            background-color: white;
            background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #fff), color-stop(100%, #dcdcdc));
            background: -webkit-linear-gradient(top, #fff 0%, #dcdcdc 100%);
            background: -moz-linear-gradient(top, #fff 0%, #dcdcdc 100%);
            /*background: -ms-linear-gradient(top, #fff 0%, #dcdcdc 100%);*/
            background: -o-linear-gradient(top, #fff 0%, #dcdcdc 100%);
            background: linear-gradient(to bottom, #fff 0%, #dcdcdc 100%)
        }

        .dataTables_wrapper .dataTables_paginate .paginate_button.disabled, .dataTables_wrapper .dataTables_paginate .paginate_button.disabled:hover, .dataTables_wrapper .dataTables_paginate .paginate_button.disabled:active {
            cursor: default;
            color: #007bff !important;
            border: 1px solid transparent;
            background: transparent;
            box-shadow: none
        }

        .dataTables_wrapper .dataTables_paginate .paginate_button:hover {
            color: white !important;
            border: 1px solid #007bff;
            background-color: #007bff;
            background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #007bff), color-stop(100%, #007bff));
            background: -webkit-linear-gradient(top, #007bff 0%, #007bff 100%);
            background: -moz-linear-gradient(top, #007bff 0%, #007bff 100%);
            /*background: -ms-linear-gradient(top, #007bff 0%, #007bff 100%);*/
            background: -o-linear-gradient(top, #007bff 0%, #007bff 100%);
            background: linear-gradient(to bottom, #585858 0%, #007bff 100%)
        }

        .dataTables_wrapper .dataTables_paginate .paginate_button:active {
            outline: none;
            background-color: #007bff;
            background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #2b2b2b), color-stop(100%, #007bff));
            background: -webkit-linear-gradient(top, #007bff 0%, #007bff 100%);
            background: -moz-linear-gradient(top, #007bff 0%, #007bff 100%);
            /*background: -ms-linear-gradient(top, #007bff 0%, #0c0c0c 100%);*/
            background: -o-linear-gradient(top, #2b2b2b 0%, #0c0c0c 100%);
            background: linear-gradient(to bottom, #2b2b2b 0%, #0c0c0c 100%);
            box-shadow: inset 0 0 3px #007bff
        }

    .dataTables_wrapper .dataTables_paginate .ellipsis {
        padding: 0 1em
    }

    .dataTables_wrapper .dataTables_processing {
        position: absolute;
        top: 50%;
        left: 50%;
        width: 100%;
        height: 40px;
        margin-left: -50%;
        margin-top: -25px;
        padding-top: 20px;
        text-align: center;
        font-size: 1.2em;
        background-color: white;
        background: -webkit-gradient(linear, left top, right top, color-stop(0%, rgba(255,255,255,0)), color-stop(25%, rgba(255,255,255,0.9)), color-stop(75%, rgba(255,255,255,0.9)), color-stop(100%, rgba(255,255,255,0)));
        background: -webkit-linear-gradient(left, rgba(255,255,255,0) 0%, rgba(255,255,255,0.9) 25%, rgba(255,255,255,0.9) 75%, rgba(255,255,255,0) 100%);
        background: -moz-linear-gradient(left, rgba(255,255,255,0) 0%, rgba(255,255,255,0.9) 25%, rgba(255,255,255,0.9) 75%, rgba(255,255,255,0) 100%);
        /*background: -ms-linear-gradient(left, rgba(255,255,255,0) 0%, rgba(255,255,255,0.9) 25%, rgba(255,255,255,0.9) 75%, rgba(255,255,255,0) 100%);*/
        background: -o-linear-gradient(left, rgba(255,255,255,0) 0%, rgba(255,255,255,0.9) 25%, rgba(255,255,255,0.9) 75%, rgba(255,255,255,0) 100%);
        background: linear-gradient(to right, rgba(255,255,255,0) 0%, rgba(255,255,255,0.9) 25%, rgba(255,255,255,0.9) 75%, rgba(255,255,255,0) 100%)
    }

    .dataTables_wrapper .dataTables_length, .dataTables_wrapper .dataTables_filter, .dataTables_wrapper .dataTables_info, .dataTables_wrapper .dataTables_processing, .dataTables_wrapper .dataTables_paginate {
        color: #333
    }

    .dataTables_wrapper .dataTables_scroll {
        clear: both
    }

        .dataTables_wrapper .dataTables_scroll div.dataTables_scrollBody {
            *margin-top: -1px;
            -webkit-overflow-scrolling: touch
        }

            .dataTables_wrapper .dataTables_scroll div.dataTables_scrollBody > table > thead > tr > th, .dataTables_wrapper .dataTables_scroll div.dataTables_scrollBody > table > thead > tr > td, .dataTables_wrapper .dataTables_scroll div.dataTables_scrollBody > table > tbody > tr > th, .dataTables_wrapper .dataTables_scroll div.dataTables_scrollBody > table > tbody > tr > td {
                vertical-align: middle
            }

                .dataTables_wrapper .dataTables_scroll div.dataTables_scrollBody > table > thead > tr > th > div.dataTables_sizing, .dataTables_wrapper .dataTables_scroll div.dataTables_scrollBody > table > thead > tr > td > div.dataTables_sizing, .dataTables_wrapper .dataTables_scroll div.dataTables_scrollBody > table > tbody > tr > th > div.dataTables_sizing, .dataTables_wrapper .dataTables_scroll div.dataTables_scrollBody > table > tbody > tr > td > div.dataTables_sizing {
                    height: 0;
                    overflow: hidden;
                    margin: 0 !important;
                    padding: 0 !important
                }

    .dataTables_wrapper.no-footer .dataTables_scrollBody {
        border-bottom: 1px solid #007bff
    }

    .dataTables_wrapper.no-footer div.dataTables_scrollHead table.dataTable, .dataTables_wrapper.no-footer div.dataTables_scrollBody > table {
        border-bottom: none
    }

    .dataTables_wrapper:after {
        visibility: hidden;
        display: block;
        content: "";
        clear: both;
        height: 0
    }

    @@media screen and (max-width: 767px) {
        .dataTables_wrapper .dataTables_info, .dataTables_wrapper .dataTables_paginate {
            float: none;
            text-align: center
        }

        .dataTables_wrapper .dataTables_paginate {
            margin-top: 0.5em
        }
    }

    @@media screen and (max-width: 640px) {
        .dataTables_wrapper .dataTables_length, .dataTables_wrapper .dataTables_filter {
            float: none;
            text-align: center
        }

        .dataTables_wrapper .dataTables_filter {
            margin-top: 0.5em
        }
    }
</style>