QuanLiCuaHang/Areas/Manager/Controllers/LoaiDVController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuanLiCuaHang.Areas.Manager.Data;

namespace QuanLiCuaHang.Areas.Manager.Controllers
{
    public class LoaiDVController : Controller
    {
        private QUANLYCUAHANGEntity db = new QUANLYCUAHANGEntity();

        // GET: Manager/LoaiDV
        public ActionResult Index()
        {
            var lOAIDICHVU = new LOAIDV();
            return View(lOAIDICHVU);
        }


        [HttpPost]
        public ActionResult Index([Bind(Include = "MaLoaiDV,TenLoaiDV,DonGiaDV")] LOAIDV lOAIDV)
        {
            if (ModelState.IsValid)
            {
                db.LOAIDVs.Add(lOAIDV);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(lOAIDV);
        }



        // GET: Manager/LoaiDV/Details/5
        public ActionResult Details()
        {
            return View(db.LOAIDVs.ToList());
        }

        public JsonResult IsTenDVAvailable(string TenLoaiDV)
        {
            return Json(!db.LOAIDVs.Any(x => x.TenLoaiDV == TenLoaiDV), JsonRequestBehavior.AllowGet);

        }

        // GET: Manager/LoaiDV/Create


        // GET: Manager/LoaiDV/Edit/5

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuanLiCuaHang/Areas/Manager/Views/LoaiDV/Details.cshtml
@model IEnumerable<QuanLiCuaHang.Areas.Manager.Data.LOAIDV>
<div class="card mb-4">

    <div class="card-header"><b>DANH SÁCH LOẠI DỊCH VỤ</b></div>
    <div class="card-body">

        <div class="table-responsive">
            <table class="table table-bordered table-striped mb-none" id="" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Mã loại dịch vụ</th>
                        <th>Tên loại dịch vụ</th>
                        <th>Đơn giá</th>
                    </tr>
                </thead>
                <tbody>


                    @foreach (var item in Model)
                    {

                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.MaLoaiDV)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.TenLoaiDV)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DonGiaDV)
                            </td>
                     
                        </tr>

                    }

                </tbody>
            </table>
        </div>
    </div>
</div>

QuanLiCuaHang/Areas/Manager/Views/LoaiDV/Index.cshtml
@model QuanLiCuaHang.Areas.Manager.Data.LOAIDV

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Manager/Views/Shared/_Layout.cshtml";
}



<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        $("#submit").click(function (event) {
            var error_free = true;
            if ($(".input-validation-error").length != 0) {
                error_free = false;
            }

            if (parseFloat($("#DonGiaDV").val()) <= 0) {
                error_free = false;
            }

            if ($("#TenLoaiDV").val() == '') {
                error_free = false;
            }
            if (!error_free) {
                event.preventDefault();
                swal({
                    title: "Lỗi !",
                    text: "Thêm mới thất bại!",
                    icon: "error",
                    button: "Đồng ý!",
                });
            }
            else {
                swal({
                    title: "Thành công !",
                    text: "Thêm mới thành công!",
                    icon: "success",
                    button: "Đồng ý!",
                });
            }
        });
    });
</script>


@* CSS Begin *@
<style>
    #nhapphieu {
        text-align: center;
        color: purple;
        font-size: 35px;
        font-weight: bold;
        /*border: 1px solid #ddd;
            background-color: forestgreen;*/
        padding: 0px 0px;
        margin: 0px 290px;
    }
</style>
<h1 id="nhapphieu"> LOẠI DỊCH VỤ </h1>
<br />



<head>
    <meta charset="utf-8" />

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Danh sách các loại sản phẩm</title>
    <link href="~/Assets/Manager/dist/css/styles.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />

    <!-- Vendor CSS -->
    <link rel="stylesheet" href="~/Assets/Manager/dist/assets/vendor/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="~/Assets/Manager/dist/assets/vendor/magnific-popup/magnific-popup.css" />


</head>

<main>
    @using (Html.BeginForm("Index", "LoaiDV", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="container-fluid">

            <div col="mb-4">



                <div class="alert alert-danger" id="danger-alert">
                    <a href="#" class="close" data-hide="alert" aria-label="close">&times;</a>
                </div>
                <div class="card mb-4">

                    <div class="card-header"><b>THÊM MỚI LOẠI DỊCH VỤ</b></div>
                    <div class="card-body">
                        <form action="/action_page.php" class="needs-validation" novalidate>
                            <div class="form-row">
                                <div class="form-group col-sm-3" hidden>
                                    <label>Mã loại dịch vụ</label>


                                    @Html.EditorFor(model => model.MaLoaiDV, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.MaLoaiDV, "", new { @class = "text-danger" })

                                </div>

                                <div class="form-group col-sm-3">
                                    <label>Tên loại dịch vụ</label>

                                    @*<input type="text" class="form-control" placeholder="Nhập tên loại dịch vụ" id="ten" required>*@
                                    @Html.EditorFor(model => model.TenLoaiDV, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.TenLoaiDV, "", new { @class = "text-danger" })

                                </div>

                                <div class="form-group col-sm-3">
                                    <label>Đơn giá dịch vụ</label>


                                    @Html.EditorFor(model => model.DonGiaDV, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.DonGiaDV, "", new { @class = "text-danger" })
                                    <div class="invalid-feedback">Vui lòng nhập đầy đủ thông tin về đơn giá dịch vụ</div>
                                </div>
                            </div>







                            <button id="submit" type="submit" class="btn btn-primary">Thêm</button>
                        </form>
                    </div>
                </div>

            </div>

            @Html.Action("Details")
        </div>
    }



</main>

<link rel="stylesheet" href="~Assets/Manager/dist/assets/stylesheets/theme.css" />

<!-- Vendor -->
<script src="~/Assets/Manager/dist/assets/vendor/jquery/jquery.js"></script>
<script src="~/Assets/Manager/dist/assets/vendor/jquery-browser-mobile/jquery.browser.mobile.js"></script>
<script src="~/Assets/Manager/dist/assets/vendor/bootstrap/js/bootstrap.js"></script>
<script src="~/Assets/Manager/dist/assets/vendor/nanoscroller/nanoscroller.js"></script>
<script src="~/Assets/Manager/dist/assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
<script src="~/Assets/Manager/dist/assets/vendor/magnific-popup/magnific-popup.js"></script>
<script src="~/Assets/Manager/dist/assets/vendor/jquery-placeholder/jquery.placeholder.js"></script>

<!-- Specific Page Vendor -->
<script src="~/Assets/Manager/dist/assets/vendor/select2/select2.js"></script>
<script src="~/Assets/Manager/dist/assets/vendor/jquery-datatables/media/js/jquery.dataTables.js"></script>

<!-- Examples -->
<script src="~/Assets/Manager/dist/assets/javascripts/tables/examples.datatables.editable.js"></script>

<script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
<script src="~/Assets/Manager/dist/js/scripts.js"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>


<style>
    .dataTables_paginate {
        float: right;
        text-align: right;
        padding-top: 0.25em
    }

    .dataTables_wrapper .dataTables_paginate .paginate_button {
        box-sizing: border-box;
        display: inline-block;
        min-width: 1.5em;
        padding: 0.5em 1em;
        margin-left: 2px;
        text-align: center;
        text-decoration: none !important;
        cursor: pointer;
        /**cursor: hand;*/
        color: #007bff !important;
        border: 1px solid transparent;
        border-radius: 2px
    }

        .dataTables_wrapper .dataTables_paginate .paginate_button.current, .dataTables_wrapper .dataTables_paginate .paginate_button.current:hover {
            color: #333 !important;
            border: 1px solid #979797;
            background-color: white;
            background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #fff), color-stop(100%, #dcdcdc));
            background: -webkit-linear-gradient(top, #fff 0%, #dcdcdc 100%);
            background: -moz-linear-gradient(top, #fff 0%, #dcdcdc 100%);
            /*background: -ms-linear-gradient(top, #fff 0%, #dcdcdc 100%);*/
            background: -o-linear-gradient(top, #fff 0%, #dcdcdc 100%);
            background: linear-gradient(to bottom, #fff 0%, #dcdcdc 100%)
        }

        .dataTables_wrapper .dataTables_paginate .paginate_button.disabled, .dataTables_wrapper .dataTables_paginate .paginate_button.disabled:hover, .dataTables_wrapper .dataTables_paginate .paginate_button.disabled:active {
            cursor: default;
            color: #007bff !important;
            border: 1px solid transparent;
            background: transparent;
            box-shadow: none
        }

        .dataTables_wrapper .dataTables_paginate .paginate_button:hover {
            color: white !important;
            border: 1px solid #007bff;
            background-color: #007bff;
            background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #007bff), color-stop(100%, #007bff));
            background: -webkit-linear-gradient(top, #007bff 0%, #007bff 100%);
            background: -moz-linear-gradient(top, #007bff 0%, #007bff 100%);
            /*background: -ms-linear-gradient(top, #007bff 0%, #007bff 100%);*/
            background: -o-linear-gradient(top, #007bff 0%, #007bff 100%);
            background: linear-gradient(to bottom, #585858 0%, #007bff 100%)
        }

        .dataTables_wrapper .dataTables_paginate .paginate_button:active {
            outline: none;
            background-color: #007bff;
            background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #2b2b2b), color-stop(100%, #007bff));
            background: -webkit-linear-gradient(top, #007bff 0%, #007bff 100%);
            background: -moz-linear-gradient(top, #007bff 0%, #007bff 100%);
            /*background: -ms-linear-gradient(top, #007bff 0%, #0c0c0c 100%);*/
            background: -o-linear-gradient(top, #2b2b2b 0%, #0c0c0c 100%);
            background: linear-gradient(to bottom, #2b2b2b 0%, #0c0c0c 100%);
            box-shadow: inset 0 0 3px #007bff
        }

    .dataTables_wrapper .dataTables_paginate .ellipsis {
        padding: 0 1em
    }

    .dataTables_wrapper .dataTables_processing {
        position: absolute;
        top: 50%;
        left: 50%;
        width: 100%;
        height: 40px;
        margin-left: -50%;
        margin-top: -25px;
        padding-top: 20px;
        text-align: center;
        font-size: 1.2em;
        background-color: white;
        background: -webkit-gradient(linear, left top, right top, color-stop(0%, rgba(255,255,255,0)), color-stop(25%, rgba(255,255,255,0.9)), color-stop(75%, rgba(255,255,255,0.9)), color-stop(100%, rgba(255,255,255,0)));
        background: -webkit-linear-gradient(left, rgba(255,255,255,0) 0%, rgba(255,255,255,0.9) 25%, rgba(255,255,255,0.9) 75%, rgba(255,255,255,0) 100%);
        background: -moz-linear-gradient(left, rgba(255,255,255,0) 0%, rgba(255,255,255,0.9) 25%, rgba(255,255,255,0.9) 75%, rgba(255,255,255,0) 100%);
        /*background: -ms-linear-gradient(left, rgba(255,255,255,0) 0%, rgba(255,255,255,0.9) 25%, rgba(255,255,255,0.9) 75%, rgba(255,255,255,0) 100%);*/
        background: -o-linear-gradient(left, rgba(255,255,255,0) 0%, rgba(255,255,255,0.9) 25%, rgba(255,255,255,0.9) 75%, rgba(255,255,255,0) 100%);
        background: linear-gradient(to right, rgba(255,255,255,0) 0%, rgba(255,255,255,0.9) 25%, rgba(255,255,255,0.9) 75%, rgba(255,255,255,0) 100%)
    }

    .dataTables_wrapper .dataTables_length, .dataTables_wrapper .dataTables_filter, .dataTables_wrapper .dataTables_info, .dataTables_wrapper .dataTables_processing, .dataTables_wrapper .dataTables_paginate {
        color: #333
    }

    .dataTables_wrapper .dataTables_scroll {
        clear: both
    }

        .dataTables_wrapper .dataTables_scroll div.dataTables_scrollBody {
            *margin-top: -1px;
            -webkit-overflow-scrolling: touch
        }

            .dataTables_wrapper .dataTables_scroll div.dataTables_scrollBody > table > thead > tr > th, .dataTables_wrapper .dataTables_scroll div.dataTables_scrollBody > table > thead > tr > td, .dataTables_wrapper .dataTables_scroll div.dataTables_scrollBody > table > tbody > tr > th, .dataTables_wrapper .dataTables_scroll div.dataTables_scrollBody > table > tbody > tr > td {
                vertical-align: middle
            }

                .dataTables_wrapper .dataTables_scroll div.dataTables_scrollBody > table > thead > tr > th > div.dataTables_sizing, .dataTables_wrapper .dataTables_scroll div.dataTables_scrollBody > table > thead > tr > td > div.dataTables_sizing, .dataTables_wrapper .dataTables_scroll div.dataTables_scrollBody > table > tbody > tr > th > div.dataTables_sizing, .dataTables_wrapper .dataTables_scroll div.dataTables_scrollBody > table > tbody > tr > td > div.dataTables_sizing {
                    height: 0;
                    overflow: hidden;
                    margin: 0 !important;
                    padding: 0 !important
                }

    .dataTables_wrapper.no-footer .dataTables_scrollBody {
        border-bottom: 1px solid #007bff
    }

    .dataTables_wrapper.no-footer div.dataTables_scrollHead table.dataTable, .dataTables_wrapper.no-footer div.dataTables_scrollBody > table {
        border-bottom: none
    }

    .dataTables_wrapper:after {
        visibility: hidden;
        display: block;
        content: "";
        clear: both;
        height: 0
    }

    @@media screen and (max-width: 767px) {
        .dataTables_wrapper .dataTables_info, .dataTables_wrapper .dataTables_paginate {
            float: none;
            text-align: center
        }

        .dataTables_wrapper .dataTables_paginate {
            margin-top: 0.5em
        }
    }

    @@media screen and (max-width: 640px) {
        .dataTables_wrapper .dataTables_length, .dataTables_wrapper .dataTables_filter {
            float: none;
            text-align: center
        }

        .dataTables_wrapper .dataTables_filter {
            margin-top: 0.5em
        }
    }
</style>