QuanLiCuaHang/Areas/Manager/Controllers/CT_PhieuMuaHangController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuanLiCuaHang.Areas.Manager.Data;
using QuanLiCuaHang.Areas.Manager.Repository;
using QuanLiCuaHang.Areas.Manager.ViewModel;

namespace QuanLiCuaHang.Areas.Manager.Controllers
{
    public class CT_PhieuMuaHangController : Controller
    {
        private QUANLYCUAHANGEntity db = new QUANLYCUAHANGEntity();

        // GET: Manager/CT_PhieuMuaHang

        // Ham lay ra don gia
        public JsonResult GetDonGia(int MaSP)
        {
            decimal UnitPrice = db.SANPHAMs.Single(d => d.MaSP == MaSP).GiaMuaVao;
            return Json(UnitPrice, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]

        //// Ham lay ra loai san pham
        public JsonResult GetLoaiSanPham(int MaSP)
        {
            int MaLoaiSanPham = db.SANPHAMs.Single(d => d.MaSP == MaSP).MaLoaiSP;
            string LoaiSanPham = db.LOAISANPHAMs.Single(m => m.MaLoaiSP == MaLoaiSanPham).TenLoaiSP;
            return Json(LoaiSanPham, JsonRequestBehavior.AllowGet);
        }

        // Ham lay ra don vi tinh
        public JsonResult GetDonViTinh(int MaSP)
        {
            int MaLoaiSanPham = db.SANPHAMs.Single(d => d.MaSP == MaSP).MaLoaiSP;
            int LoaiSanPham = db.LOAISANPHAMs.Single(m => m.MaLoaiSP == MaLoaiSanPham).MaDVT;
            string DonViTinh = db.DONVITINHs.Single(m => m.MaDVT == LoaiSanPham).TenDVT;

            return Json(DonViTinh, JsonRequestBehavior.AllowGet);
        }

        // Ham lay ra số lượng tồn
        public JsonResult GetSoLuongTon(int MaSP)
        {
            int SoLuongTon = db.SANPHAMs.Single(d => d.MaSP == MaSP).SoLuongTon;
            return Json(SoLuongTon, JsonRequestBehavior.AllowGet);
        }

        // Hàm lấy ra số điện thoại
        public JsonResult GetSDT(int MaNCC)
        {
            var SDT = db.NHACUNGCAPs.Single(d => d.MaNCC == MaNCC).SDT;
            return Json(SDT, JsonRequestBehavior.AllowGet);
        }

        // Hàm lấy ra địa chỉ
        public JsonResult GetDiaChi(int MaNCC)
        {
            var DiaChi = db.NHACUNGCAPs.Single(d => d.MaNCC == MaNCC).DiaChi;
            return Json(DiaChi, JsonRequestBehavior.AllowGet);
        }



        public JsonResult GetItem(int itemID)
        {
            decimal UnitPrice = db.SANPHAMs.Single(d => d.MaSP == itemID).GiaBanRa;
            return Json(UnitPrice, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult Create([System.Web.Http.FromBody] PhieuMuaHangViewModel phieuMuaHang)
        {
            CT_PhieuMuaHangRepository cT_PhieuMuaHangRepository = new CT_PhieuMuaHangRepository();
            cT_PhieuMuaHangRepository.AddCT_PhieuMuaHang(phieuMuaHang);

            return Json(data: "Tạo phiếu bán hàng thành công", JsonRequestBehavior.AllowGet);
        }

        public ActionResult Index()
        {
            var cHITIET_PMH = db.CHITIET_PMH.Include(c => c.PHIEUMUAHANG).Include(c => c.SANPHAM);
            return View(cHITIET_PMH.ToList());
        }

        // GET: Manager/CT_PhieuMuaHang/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var CT_PhieuMuaHang = db.CHITIET_PMH.Include(b => b.PHIEUMUAHANG).Include(c => c.SANPHAM);
            var result = (CT_PhieuMuaHang.Where(x => x.MaPMH == id)).ToList();
            return View(result);

        }

        // GET: Manager/CT_PhieuMuaHang/Create
        public ActionResult Create()
        {
            ViewBag.MaPMH = new SelectList(db.PHIEUMUAHANGs, "MaPMH", "MaPMH");
            ViewBag.MaSP = new SelectList(db.SANPHAMs, "MaSP", "TenSanPham");
            ViewBag.MaNCC = new SelectList(db.NHACUNGCAPs, "MaNCC", "TenNCC");
            return View();
        }

        // POST: Manager/CT_PhieuMuaHang/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "MaPMH,MaSP,SoLuong,DonGia,ThanhTien")] CHITIET_PMH cHITIET_PMH)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.CHITIET_PMH.Add(cHITIET_PMH);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    ViewBag.MaPMH = new SelectList(db.PHIEUMUAHANGs, "MaPMH", "MaPMH", cHITIET_PMH.MaPMH);
        //    ViewBag.MaSP = new SelectList(db.SANPHAMs, "MaSP", "TenSanPham", cHITIET_PMH.MaSP);
        //    return View(cHITIET_PMH);
        //}

        // GET: Manager/CT_PhieuMuaHang/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CHITIET_PMH cHITIET_PMH = db.CHITIET_PMH.Find(id);
            if (cHITIET_PMH == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaPMH = new SelectList(db.PHIEUMUAHANGs, "MaPMH", "MaPMH", cHITIET_PMH.MaPMH);
            ViewBag.MaSP = new SelectList(db.SANPHAMs, "MaSP", "TenSanPham", cHITIET_PMH.MaSP);
            return View(cHITIET_PMH);
        }

        // POST: Manager/CT_PhieuMuaHang/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaPMH,MaSP,SoLuong,DonGia,ThanhTien")] CHITIET_PMH cHITIET_PMH)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cHITIET_PMH).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaPMH = new SelectList(db.PHIEUMUAHANGs, "MaPMH", "MaPMH", cHITIET_PMH.MaPMH);
            ViewBag.MaSP = new SelectList(db.SANPHAMs, "MaSP", "TenSanPham", cHITIET_PMH.MaSP);
            return View(cHITIET_PMH);
        }

        // GET: Manager/CT_PhieuMuaHang/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CHITIET_PMH cHITIET_PMH = db.CHITIET_PMH.Find(id);
            if (cHITIET_PMH == null)
            {
                return HttpNotFound();
            }
            return View(cHITIET_PMH);
        }

        // POST: Manager/CT_PhieuMuaHang/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CHITIET_PMH cHITIET_PMH = db.CHITIET_PMH.Find(id);
            db.CHITIET_PMH.Remove(cHITIET_PMH);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuanLiCuaHang/Areas/Manager/Views/PhieuMuaHang/Index.cshtml
@model IEnumerable<QuanLiCuaHang.Areas.Manager.Data.PHIEUMUAHANG>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Manager/Views/Shared/_Layout.cshtml";
}

@* CSS Begin *@
<style>

    #nhapphieu {
        text-align: center;
        color: purple;
        font-size: 35px;
        font-weight: bold;
        /*border: 1px solid #ddd;
            background-color: forestgreen;*/
        padding: 0px 0px;
        margin: 0px 290px;
    }

</style>

<h1 id="nhapphieu"> TRA CỨU PHIẾU MUA HÀNG </h1>
<br />



<head>
    <meta charset="utf-8" />

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Danh sách các loại sản phẩm</title>
    <link href="~/Assets/Manager/dist/css/styles.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" crossorigin="anonymous"></script>*@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />

    <!-- Vendor CSS -->
    <link rel="stylesheet" href="~/Assets/Manager/dist/assets/vendor/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="~/Assets/Manager/dist/assets/vendor/magnific-popup/magnific-popup.css" />


</head>

<main>

    <div class="card mb-4">

        <div class="card-header"><b>TIÊU CHÍ TRA CỨU</b></div>
        <div class="card-body">
            <form action="/action_page.php" class="needs-validation" novalidate>
                <div class="form-row">

                    <div class="form-group col-sm-3">
                        <label>Số phiếu</label>

                        <input type="number" class="form-control" id="so_phieu" required>
                    </div>

                    <div class="form-group col-sm-3">
                        <label>Nhà cung cấp</label>

                        <input type="text" class="form-control" id="nha_cung_cap" required>
                    </div>

                    <div class="form-group col-sm-3">
                        <label>Ngày lập</label>

                        <input type="text" class="form-control" id="ngay_lap" required>
                    </div>

                    <div class="form-group col-sm-3">
                        <label> Tổng tiền </label>

                         <input type="text" class="form-control" id="dia_chi" required>
                    </div>

                

                </div>

                

            </form>
        </div>

    </div>


    <div class="card mb-4">

        <div class="card-header"><b>DANH SÁCH HÓA ĐƠN</b></div>
        <div class="card-body">

            <div class="table-responsive">
                <table class="table table-bordered table-striped mb-none" id="tra_cuu_mua_hang" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Số phiếu</th>
                            <th>Nhà cung cấp</th>
                            <th>Ngày lập</th>
                            <th> Tổng tiền </th>
                            <th>Thao tác</th>
                        </tr>
                    </thead>
                    <tbody>


                        @foreach (var item in Model)
                        {

                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.MaPMH)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.NHACUNGCAP.TenNCC)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.NgayLap)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TongTien)
                                </td>
                                <td class="actions" style="text-align:center">
                                    <a href="@Url.Action("Details","CT_PhieuMuaHang", new { id = item.MaPMH })">
                                        <i type="button" class="fa fa-search-plus fa-2x"> </i>
                                    </a>
                                </td>
                            </tr>

                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>

</main>

<link rel="stylesheet" href="~Assets/Manager/dist/assets/stylesheets/theme.css" />

<!-- Vendor -->
<script src="~/Assets/Manager/dist/assets/vendor/jquery/jquery.js"></script>
<script src="~/Assets/Manager/dist/assets/vendor/jquery-browser-mobile/jquery.browser.mobile.js"></script>
<script src="~/Assets/Manager/dist/assets/vendor/bootstrap/js/bootstrap.js"></script>
<script src="~/Assets/Manager/dist/assets/vendor/nanoscroller/nanoscroller.js"></script>
<script src="~/Assets/Manager/dist/assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
<script src="~/Assets/Manager/dist/assets/vendor/magnific-popup/magnific-popup.js"></script>
<script src="~/Assets/Manager/dist/assets/vendor/jquery-placeholder/jquery.placeholder.js"></script>

<!-- Specific Page Vendor -->
<script src="~/Assets/Manager/dist/assets/vendor/select2/select2.js"></script>
<script src="~/Assets/Manager/dist/assets/vendor/jquery-datatables/media/js/jquery.dataTables.js"></script>

<!-- Examples -->
<script src="~/Assets/Manager/dist/assets/javascripts/tables/tra-cuu-mua-hang.js"></script>

<script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
<script src="~/Assets/Manager/dist/js/scripts.js"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>


<style>

    .dataTables_paginate {
        float: right;
        text-align: right;
        padding-top: 0.25em
    }

    .dataTables_wrapper .dataTables_paginate .paginate_button {
        box-sizing: border-box;
        display: inline-block;
        min-width: 1.5em;
        padding: 0.5em 1em;
        margin-left: 2px;
        text-align: center;
        text-decoration: none !important;
        cursor: pointer;
        /**cursor: hand;*/
        color: #007bff !important;
        border: 1px solid transparent;
        border-radius: 2px
    }

        .dataTables_wrapper .dataTables_paginate .paginate_button.current, .dataTables_wrapper .dataTables_paginate .paginate_button.current:hover {
            color: #333 !important;
            border: 1px solid #979797;
            background-color: white;
            background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #fff), color-stop(100%, #dcdcdc));
            background: -webkit-linear-gradient(top, #fff 0%, #dcdcdc 100%);
            background: -moz-linear-gradient(top, #fff 0%, #dcdcdc 100%);
            /*background: -ms-linear-gradient(top, #fff 0%, #dcdcdc 100%);*/
            background: -o-linear-gradient(top, #fff 0%, #dcdcdc 100%);
            background: linear-gradient(to bottom, #fff 0%, #dcdcdc 100%)
        }

        .dataTables_wrapper .dataTables_paginate .paginate_button.disabled, .dataTables_wrapper .dataTables_paginate .paginate_button.disabled:hover, .dataTables_wrapper .dataTables_paginate .paginate_button.disabled:active {
            cursor: default;
            color: #007bff !important;
            border: 1px solid transparent;
            background: transparent;
            box-shadow: none
        }

        .dataTables_wrapper .dataTables_paginate .paginate_button:hover {
            color: white !important;
            border: 1px solid #007bff;
            background-color: #007bff;
            background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #007bff), color-stop(100%, #007bff));
            background: -webkit-linear-gradient(top, #007bff 0%, #007bff 100%);
            background: -moz-linear-gradient(top, #007bff 0%, #007bff 100%);
            /*background: -ms-linear-gradient(top, #007bff 0%, #007bff 100%);*/
            background: -o-linear-gradient(top, #007bff 0%, #007bff 100%);
            background: linear-gradient(to bottom, #585858 0%, #007bff 100%)
        }

        .dataTables_wrapper .dataTables_paginate .paginate_button:active {
            outline: none;
            background-color: #007bff;
            background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #2b2b2b), color-stop(100%, #007bff));
            background: -webkit-linear-gradient(top, #007bff 0%, #007bff 100%);
            background: -moz-linear-gradient(top, #007bff 0%, #007bff 100%);
            /*background: -ms-linear-gradient(top, #007bff 0%, #0c0c0c 100%);*/
            background: -o-linear-gradient(top, #2b2b2b 0%, #0c0c0c 100%);
            background: linear-gradient(to bottom, #2b2b2b 0%, #0c0c0c 100%);
            box-shadow: inset 0 0 3px #007bff
        }

    .dataTables_wrapper .dataTables_paginate .ellipsis {
        padding: 0 1em
    }

    .dataTables_wrapper .dataTables_processing {
        position: absolute;
        top: 50%;
        left: 50%;
        width: 100%;
        height: 40px;
        margin-left: -50%;
        margin-top: -25px;
        padding-top: 20px;
        text-align: center;
        font-size: 1.2em;
        background-color: white;
        background: -webkit-gradient(linear, left top, right top, color-stop(0%, rgba(255,255,255,0)), color-stop(25%, rgba(255,255,255,0.9)), color-stop(75%, rgba(255,255,255,0.9)), color-stop(100%, rgba(255,255,255,0)));
        background: -webkit-linear-gradient(left, rgba(255,255,255,0) 0%, rgba(255,255,255,0.9) 25%, rgba(255,255,255,0.9) 75%, rgba(255,255,255,0) 100%);
        background: -moz-linear-gradient(left, rgba(255,255,255,0) 0%, rgba(255,255,255,0.9) 25%, rgba(255,255,255,0.9) 75%, rgba(255,255,255,0) 100%);
        /*background: -ms-linear-gradient(left, rgba(255,255,255,0) 0%, rgba(255,255,255,0.9) 25%, rgba(255,255,255,0.9) 75%, rgba(255,255,255,0) 100%);*/
        background: -o-linear-gradient(left, rgba(255,255,255,0) 0%, rgba(255,255,255,0.9) 25%, rgba(255,255,255,0.9) 75%, rgba(255,255,255,0) 100%);
        background: linear-gradient(to right, rgba(255,255,255,0) 0%, rgba(255,255,255,0.9) 25%, rgba(255,255,255,0.9) 75%, rgba(255,255,255,0) 100%)
    }

    .dataTables_wrapper .dataTables_length, .dataTables_wrapper .dataTables_filter, .dataTables_wrapper .dataTables_info, .dataTables_wrapper .dataTables_processing, .dataTables_wrapper .dataTables_paginate {
        color: #333
    }

    .dataTables_wrapper .dataTables_scroll {
        clear: both
    }

        .dataTables_wrapper .dataTables_scroll div.dataTables_scrollBody {
            *margin-top: -1px;
            -webkit-overflow-scrolling: touch
        }

            .dataTables_wrapper .dataTables_scroll div.dataTables_scrollBody > table > thead > tr > th, .dataTables_wrapper .dataTables_scroll div.dataTables_scrollBody > table > thead > tr > td, .dataTables_wrapper .dataTables_scroll div.dataTables_scrollBody > table > tbody > tr > th, .dataTables_wrapper .dataTables_scroll div.dataTables_scrollBody > table > tbody > tr > td {
                vertical-align: middle
            }

                .dataTables_wrapper .dataTables_scroll div.dataTables_scrollBody > table > thead > tr > th > div.dataTables_sizing, .dataTables_wrapper .dataTables_scroll div.dataTables_scrollBody > table > thead > tr > td > div.dataTables_sizing, .dataTables_wrapper .dataTables_scroll div.dataTables_scrollBody > table > tbody > tr > th > div.dataTables_sizing, .dataTables_wrapper .dataTables_scroll div.dataTables_scrollBody > table > tbody > tr > td > div.dataTables_sizing {
                    height: 0;
                    overflow: hidden;
                    margin: 0 !important;
                    padding: 0 !important
                }

    .dataTables_wrapper.no-footer .dataTables_scrollBody {
        border-bottom: 1px solid #007bff
    }

    .dataTables_wrapper.no-footer div.dataTables_scrollHead table.dataTable, .dataTables_wrapper.no-footer div.dataTables_scrollBody > table {
        border-bottom: none
    }

    .dataTables_wrapper:after {
        visibility: hidden;
        display: block;
        content: "";
        clear: both;
        height: 0
    }

    @@media screen and (max-width: 767px) {
        .dataTables_wrapper .dataTables_info, .dataTables_wrapper .dataTables_paginate {
            float: none;
            text-align: center
        }

        .dataTables_wrapper .dataTables_paginate {
            margin-top: 0.5em
        }
    }

    @@media screen and (max-width: 640px) {
        .dataTables_wrapper .dataTables_length, .dataTables_wrapper .dataTables_filter {
            float: none;
            text-align: center
        }

        .dataTables_wrapper .dataTables_filter {
            margin-top: 0.5em
        }
    }
</style>